### ISSUE TITLE
版本

### ISSUE THREAD

**Issue by Openfan-Alex** [fanbook-wangdage/fb-jqrkzq-app#1]
目前的发行版本是？

**Comment by wangdage12** [comment]
- app.aia：最新版，但是开发了一半  
- kzq2.aia：距离已发布版本最近的旧版

**Comment by Openfan-Alex** [comment]
有打包版本吗

**Comment by wangdage12** [comment]
https://github.com/fanbook-wangdage/fb-jqrkzq-app/releases/tag/1.9test
